version: "3.1"

services:
  main:
    image: node:14-alpine
    container_name: sld-bff-server
    ports:
      - 5000:5000
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: yarn compose:daemon
    environment:
      FASTIFY_OPTIONS: '{ "logger": true, "ignoreTrailingSlash": true }'
      HTTP_PORT: 5000
